version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/project2-0.0.1-SNAPSHOT.jar ROOT.jar
artifacts:
  files:
    - ROOT.jar
<<<<<<< HEAD
    - .ebextensions/**/*
=======
    - .ebextensions/**/*
>>>>>>> 385178f8436482d93e3c6715135e29eb034120cc
